In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import numpy as np

In [2]:
# Carregando a base de dados e criando os previsores (Variáveis independentes - X) e a classe (Variável dependente Y)
base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# Transformando a classe para o formato "dummy", pois temos uma rede neural com 3 nurônios na camada de saída
classe_dummy = to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [4]:
# Divisão da base de dados entre treinamento e teste(30% para teste e 70% para treinar)
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,  
                                                                  classe_dummy,
                                                                  test_size=0.3,
                                                                  random_state=0)

In [5]:
# Criação da estrutura da rede neural com classe Sequential (sequência de comandos)
modelo = Sequential()
# Primeira camada oculta, 5 neurônios, 4 neurônios de entrada 
modelo.add(Dense(units=5, input_dim = 4))
# Segunda camada oculta
modelo.add(Dense(units=4))
# Terceira camada oculta
# Função softmax porque temos um problema de classificação com mais de duas classes 
# (é gerada uma probabilidade em cada neurônio)
modelo.add(Dense(units=3, activation='softmax'))

c:\Users\rodri\anaconda3\envs\EstudoCienciasDeDados\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
# Visualização da estrutura da rede neural
modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
# Configuração dos parâmetros da rede neural (adam = algoritmo para atualizar os pesos e loss = cálculo do erro)
modelo.compile(optimizer= 'adam', loss='categorical_crossentropy',
               metrics= ['accuracy'])
# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(X_treinamento, y_treinamento, epochs= 1000,
           validation_data = (X_teste, y_teste))

Epoch 1/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.2854 - loss: 3.0884 - val_accuracy: 0.4000 - val_loss: 2.9597
Epoch 2/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2948 - loss: 2.9874 - val_accuracy: 0.4000 - val_loss: 2.8199
Epoch 3/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3084 - loss: 2.6935 - val_accuracy: 0.4000 - val_loss: 2.6988
Epoch 4/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3136 - loss: 2.6879 - val_accuracy: 0.4000 - val_loss: 2.5849
Epoch 5/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3011 - loss: 2.4190 - val_accuracy: 0.3556 - val_loss: 2.4814
Epoch 6/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1617 - loss: 2.4445 - val_accuracy: 0.1556 - val_loss: 2.3781
Epoch 7/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0454 - loss: 2.2606 - val_accuracy: 0.1778 - val_loss: 2.2655
Epoch 8/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.0947 - loss: 2.0737 - val_accuracy: 0.1778 - v

In [8]:
# Previsões e mudar a variável para True ou False de acordo com o treshold 0.5
previsoes = modelo.predict(X_teste)
previsoes =(previsoes > 0.5)
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [9]:
# Como é um problema de três saídas, buscando a posição que possuí o maior valor (são retornados 3 valores)
y_teste_matrix = [np.argmax(t) for t in y_teste] 
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [10]:
# Gerando matriz de confusão
confusao = confusion_matrix(y_previsao_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 12]])