In [2]:
# Importando bibliotecas
import numpy as np
import pandas as pd
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('../data/soybean.csv')
df

date plant-stand   precip     temp hail         crop-hist  \
0    october      normal  gt-norm     norm  yes       same-lst-yr   
1     august      normal  gt-norm     norm  yes  same-lst-two-yrs   
2       july      normal  gt-norm     norm  yes       same-lst-yr   
3       july      normal  gt-norm     norm  yes       same-lst-yr   
4    october      normal  gt-norm     norm  yes  same-lst-two-yrs   
..       ...         ...      ...      ...  ...               ...   
678    april           ?        ?        ?    ?                 ?   
679    april   lt-normal        ?  lt-norm    ?     diff-lst-year   
680     june   lt-normal        ?  lt-norm    ?     diff-lst-year   
681    april   lt-normal        ?  lt-norm    ?       same-lst-yr   
682     june   lt-normal        ?  lt-norm    ?       same-lst-yr   

    area-damaged    severity   seed-tmt germination  ... sclerotia fruit-pods  \
0      low-areas  pot-severe       none      90-100  ...    absent       norm   
1      scattered      severe  fungicide       80-89  ...    absent       norm   
2      scattered      severe  fungicide       lt-80  ...    absent       norm   
3      scattered      severe       none       80-89  ...    absent       norm   
4      scattered  pot-severe       none       lt-80  ...    absent       norm   
..           ...         ...        ...         ...  ...       ...        ...   
678  upper-areas           ?          ?           ?  ...         ?          ?   
679    scattered           ?          ?           ?  ...         ?        dna   
680    scattered           ?          ?           ?  ...         ?        dna   
681  whole-field           ?          ?           ?  ...         ?        dna   
682  whole-field           ?          ?           ?  ...         ?        dna   

    fruit-spots  seed mold-growth seed-discolor seed-size shriveling   roots  \
0           dna  norm      absent        absent      norm     absent    norm   
1           dna  norm      absent        absent      norm     absent    norm   
2           dna  norm      absent        absent      norm     absent    norm   
3           dna  norm      absent        absent      norm     absent    norm   
4           dna  norm      absent        absent      norm     absent    norm   
..          ...   ...         ...           ...       ...        ...     ...   
678           ?     ?           ?             ?         ?          ?       ?   
679           ?     ?           ?             ?         ?          ?  rotted   
680           ?     ?           ?             ?         ?          ?  rotted   
681           ?     ?           ?             ?         ?          ?  rotted   
682           ?     ?           ?             ?         ?          ?  rotted   

                     class  
0    diaporthe-stem-canker  
1    diaporthe-stem-canker  
2    diaporthe-stem-canker  
3    diaporthe-stem-canker  
4    diaporthe-stem-canker  
..                     ...  
678           2-4-d-injury  
679       herbicide-injury  
680       herbicide-injury  
681       herbicide-injury  
682       herbicide-injury  

[683 rows x 36 columns]

In [4]:
X = df.iloc[:,0:35].values
y = df.iloc[:,35].values

X

array([['october', 'normal', 'gt-norm', ..., 'norm', 'absent', 'norm'],
       ['august', 'normal', 'gt-norm', ..., 'norm', 'absent', 'norm'],
       ['july', 'normal', 'gt-norm', ..., 'norm', 'absent', 'norm'],
       ...,
       ['june', 'lt-normal', '?', ..., '?', '?', 'rotted'],
       ['april', 'lt-normal', '?', ..., '?', '?', 'rotted'],
       ['june', 'lt-normal', '?', ..., '?', '?', 'rotted']], dtype=object)

In [5]:
labelencoder = LabelEncoder()

for x in range(35):
    X[:, x] = labelencoder.fit_transform(X[:, x])
print(X)

[[6 2 1 ... 2 1 2]
 [2 2 1 ... 2 1 2]
 [3 2 1 ... 2 1 2]
 ...
 [4 1 0 ... 0 0 3]
 [1 1 0 ... 0 0 3]
 [4 1 0 ... 0 0 3]]


In [6]:
labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)
y

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [7]:
class_dummy = to_categorical(y)
class_dummy

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, class_dummy, test_size=0.3, random_state=0)

In [9]:
print(X_train.dtype)
print(X_test.dtype)
print(y_train.dtype)
print(y_test.dtype)

object
object
float64
float64


In [10]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [11]:
classifier = Sequential()
classifier.add(Dense(units=64, kernel_initializer='uniform', activation='relu', input_dim = 35))
classifier.add(Dense(units=32, kernel_initializer='uniform', activation='relu'))
classifier.add(Dense(units=19, kernel_initializer='uniform', activation='softmax'))
classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
classifier.fit(X_train, y_train, batch_size=5, epochs=100)

c:\Users\rodri\anaconda3\envs\EstudoCienciasDeDados\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1426 - loss: 2.8495
Epoch 2/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2461 - loss: 2.3992
Epoch 3/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3313 - loss: 2.0900
Epoch 4/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.3726 - loss: 1.8130
Epoch 5/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4053 - loss: 1.6864
Epoch 6/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5094 - loss: 1.4717
Epoch 7/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4549 - loss: 1.4082
Epoch 8/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5426 - loss: 1.2609
Epoch 9/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5878 - loss: 1.1140
Epoch 10/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6135 - loss: 1.0417
Epoch 11/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6175 - loss: 0.9788
Epoch 12/100
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy:

In [12]:
y_pred = classifier.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step  


In [13]:
y_test_matriz = [np.argmax(t) for t in y_test]
y_pred_matriz = [np.argmax(t) for t in y_pred]

In [14]:
cm = confusion_matrix(y_test_matriz, y_pred_matriz)
print(cm)

[[ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  7  0  1  0  0  0  0]
 [ 0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0 19  0  0  0  0  0  0  2  0  1  0  0  0  0]
 [ 0  0  0  0  0  0 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  1  0  0  0  0  0  0 24  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  2  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 26  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0